name: manual Workflow
on: workflow_dispatch

jobs:
  run-firdt-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some Text2"
      - name: command in multiline
        run: |
          node -v
          npm -v