name: third Workflow
on: [push]

jobs:
  run-third-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some Text2"
      - name: command in multiline
        run: |
          pwd
          ls -al
          uses actions/checkout@v4
      - name: list files
          run: |
            pwd
            ls -al